[project]
name = "final-project-mariana-ines-andrew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrew Lee", email = "andrewlee05@postech.ac.kr" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "qutip>=5.3.1",
    "scipy>=1.18.0",
]

[project.scripts]
final-project-mariana-ines-andrew = "final_project_mariana_ines_andrew:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
